#ifndef MOBIIEVENTBUSCODES_H_
#define MOBIIEVENTBUSCODES_H_

#include "qstring.h"

/*! \file */

/*
** Mobii event bus events names
*/

// -- Core features calls
#define	CORE_REQ_RESETUID		"CORE_REQ_RESETUID"
#define	CORE_REQ_RESETUSERSTOR	"CORE_REQ_RESETUSERSTOR"
#define CORE_REQ_RESETSRVSETTINGS "CORE_REQ_RESETSRVSETTINGS"

// -- Networking
#define NET_SERVER_CONNECTED "NET_SERVER_CONNECTED"
#define NET_SERVER_DISCONNECTED "NET_SERVER_DISCONNECTED"
#define NET_SERVER_ERROR "NET_SERVER_ERROR" // e.g.: connection refused
#define NET_REQUEST_UDPHOLEPUNCHING "NET_REQUEST_UDPHOLEPUNCHING"
#define NET_EXECUTE_UDPHOLEPUNCHING "NET_EXECUTE_UDPHOLEPUNCHING"
#define NET_UDPHP_SENDMOBIIPACKETUDP "NET_UDPHP_SENDMOBIIPACKETUDP"
#define NET_UDPHP_SENDJSONUDP "NET_UDPHP_SENDJSONUDP"
#define	NET_UDPHP_SERVER_RECEIVED_DGRAM "NET_UDPHP_SERVER_RECEIVED_DGRAM"
#define NET_UDPHP_RECEIVEDACK "NET_UDPHP_RECEIVEDACK"
#define NET_UDPHP_SENDACK "NET_UDPHP_SENDACK"

// -- Communication services
#define COMMSRV_PROCESS_PACKET "COMMSRV_PROCESS_PACKET"

// -- Mobile binding
#define ATTEMPT_MOBILE_BINDING "ATTEMPT_MOBILE_BINDING"
#define NET_MOBILE_CONNECTED "NET_MOBILE_CONNECTED"
#define NET_MOBILE_DISCONNECTED "NET_MOBILE_DISCONNECTED"
#define BINDING_ATTEMPT_OKAY "BINDING_ATTEMPT_OKAY"
#define BINDING_ATTEMPT_FAILED "BINDING_ATTEMPT_FAILED"

// -- Retrieve user's mobiles history from server
#define USER_MOBILES_SENDREQ "USER_MOBILES_SENDREQ"
#define USER_MOBILES_LIST "USER_MOBILES_LIST"
#define USER_MOBILES_ADD "USER_MOBILES_ADD"
#define USER_MOBILES_DEL "USER_MOBILES_DEL"
#define USER_MOBILES_RENAME "USER_MOBILES_RENAME"

// -- UI status notification
#define SERVER_SETTINGS_NOT_SET "SERVER_SETTINGS_NOT_SET"
#define BLOCKING_OPERATION_BEGIN "BLOCKING_OPERATION_BEGIN"
#define BLOCKING_OPERATION_END "BLOCKING_OPERATION_END"
#define DISPLAY_NOTIFICATION_SYSTRAY "DISPLAY_NOTIFICATION_SYSTRAY"
#define UI_CHANGE_ACTIVE_PANEL "UI_CHANGE_ACTIVE_PANEL"

// -- Generic JSON outgoing request
#define JSON_SEND_REQUEST "SEND_JSON_REQUEST"

// -- Generic prefix for JSON actions (e.g.: "JSONINPUT_mobile_infos")
#define JSON_INPUT_PREFIX "JSONINPUT_"

// -- Notify the available features on the phone
#define FEATURES_AVAILABLE_ON_PHONE "FEATURES_AVAILABLE_ON_PHONE"

// -- Server connection
#define SERVER_ERROR_REPORT "SERVER_ERROR_REPORT"
#define CLIENT_REGISTRATION_ACK "CLIENT_REGISTRATION_ACK"
#define CONNECT_TO_SERVER "CONNECT_TO_SERVER"
#define DISCONNECT_FROM_SERVER "DISCONNECT_FROM_SERVER"

// -- User account login
#define SEND_LOGIN_INFOS "SEND_LOGIN_INFOS"
#define USER_LOGIN_OKAY "USER_LOGIN_OKAY"
#define USER_LOGIN_FAILED "USER_LOGIN_FAILED"

// -- One time client UID availability check
#define UID_REGISTRATION_OKAY "UID_REGISTRATION_OKAY"
#define UID_REGISTRATION_FAILED "UID_REGISTRATION_FAILED"

// -- checking phone number and contacts names
#define CONTACT_NAME_FOR_PHONENB "CONTACT_NAME_FOR_PHONENB"
#define CONTACT_PHONENB_FOR_NAME "CONTACT_PHONENB_FOR_NAME"

// -- Window UI signals rerouting
#define WINDOW_RESTORE "WINDOW_RESTORE"
#define APP_CLOSE "APP_CLOSE"

namespace MobiiEventBusHelper
{
	/// \brief Returns the appropriate JSON event name for a given JSON action code.
	/// Provided action codes are converted to upper case if needed, to prevent
	/// upper/lower case actions codes unconsistencies.
	/// e.g.: for a `sms' action, the JSON event name will be `JSONINPUT_SMS'.
	QString		eventNameFromAction(const QString &actionCode);
}

#endif // !MOBIIEVENTBUSCODES_H_