var annotated =
[
    [ "Json", "namespace_json.html", null ],
    [ "soci", null, [
      [ "type_conversion< SmartPhone >", "structsoci_1_1type__conversion_3_01_smart_phone_01_4.html", "structsoci_1_1type__conversion_3_01_smart_phone_01_4" ],
      [ "type_conversion< SmartPhoneName >", "structsoci_1_1type__conversion_3_01_smart_phone_name_01_4.html", "structsoci_1_1type__conversion_3_01_smart_phone_name_01_4" ],
      [ "type_conversion< User >", "structsoci_1_1type__conversion_3_01_user_01_4.html", "structsoci_1_1type__conversion_3_01_user_01_4" ],
      [ "type_conversion< Uid >", "structsoci_1_1type__conversion_3_01_uid_01_4.html", "structsoci_1_1type__conversion_3_01_uid_01_4" ],
      [ "type_conversion< UserSmartPhone >", "structsoci_1_1type__conversion_3_01_user_smart_phone_01_4.html", "structsoci_1_1type__conversion_3_01_user_smart_phone_01_4" ]
    ] ],
    [ "Acceptor", "class_acceptor.html", "class_acceptor" ],
    [ "CommunicationManager", "class_communication_manager.html", "class_communication_manager" ],
    [ "CommunicationProtocol", "class_communication_protocol.html", "class_communication_protocol" ],
    [ "Connection", "class_connection.html", "class_connection" ],
    [ "ConnectionManager", "class_connection_manager.html", "class_connection_manager" ],
    [ "ConnectionSSL", "class_connection_s_s_l.html", "class_connection_s_s_l" ],
    [ "DatabaseConnector", "class_database_connector.html", "class_database_connector" ],
    [ "DatabaseProtocol", "class_database_protocol.html", "class_database_protocol" ],
    [ "IConnection", "class_i_connection.html", "class_i_connection" ],
    [ "IdentifierAlreadyUsed", "class_identifier_already_used.html", "class_identifier_already_used" ],
    [ "InternalProtocol", "class_internal_protocol.html", "class_internal_protocol" ],
    [ "IProtocolHandler", "class_i_protocol_handler.html", "class_i_protocol_handler" ],
    [ "ISession", "class_i_session.html", "class_i_session" ],
    [ "List", "class_list.html", "class_list" ],
    [ "List< T >", "class_list_3_01_t_01_4.html", null ],
    [ "List< T, U >", "class_list_3_01_t_00_01_u_01_4.html", null ],
    [ "Map", "class_map.html", "class_map" ],
    [ "NetworkManager", "class_network_manager.html", "class_network_manager" ],
    [ "NoDataFound", "class_no_data_found.html", "class_no_data_found" ],
    [ "NoSession", "class_no_session.html", "class_no_session" ],
    [ "NoSessionException", "class_no_session_exception.html", "class_no_session_exception" ],
    [ "OpcodeException", "class_opcode_exception.html", "class_opcode_exception" ],
    [ "Packet", "class_packet.html", "class_packet" ],
    [ "PacketFactory", "class_packet_factory.html", null ],
    [ "ProtocolDispatcher", "class_protocol_dispatcher.html", "class_protocol_dispatcher" ],
    [ "ProtocolManager", "class_protocol_manager.html", "class_protocol_manager" ],
    [ "ProtocolQueue", "class_protocol_queue.html", null ],
    [ "Queue", "class_queue.html", "class_queue" ],
    [ "Queue< T >", "class_queue_3_01_t_01_4.html", null ],
    [ "RegisterProtocol", "class_register_protocol.html", "class_register_protocol" ],
    [ "ScopeLockSession", "class_scope_lock_session.html", "class_scope_lock_session" ],
    [ "Server", "class_server.html", "class_server" ],
    [ "Session", "class_session.html", "class_session" ],
    [ "SessionManager", "class_session_manager.html", "class_session_manager" ],
    [ "SessionNotFound", "class_session_not_found.html", "class_session_not_found" ],
    [ "SessionTypeException", "class_session_type_exception.html", "class_session_type_exception" ],
    [ "SmartPhone", "struct_smart_phone.html", "struct_smart_phone" ],
    [ "SmartPhoneName", "struct_smart_phone_name.html", "struct_smart_phone_name" ],
    [ "SmartPhoneProtocol", "class_smart_phone_protocol.html", "class_smart_phone_protocol" ],
    [ "SmartPhoneSession", "class_smart_phone_session.html", "class_smart_phone_session" ],
    [ "Socket", "class_socket.html", "class_socket" ],
    [ "TcpAcceptor", "class_tcp_acceptor.html", "class_tcp_acceptor" ],
    [ "TcpSocket", "class_tcp_socket.html", "class_tcp_socket" ],
    [ "TcpSSLAcceptor", "class_tcp_s_s_l_acceptor.html", "class_tcp_s_s_l_acceptor" ],
    [ "TcpSSLSocket", "class_tcp_s_s_l_socket.html", "class_tcp_s_s_l_socket" ],
    [ "UdpAcceptor", "class_udp_acceptor.html", "class_udp_acceptor" ],
    [ "UdpConnection", "class_udp_connection.html", "class_udp_connection" ],
    [ "UdpProtocol", "class_udp_protocol.html", "class_udp_protocol" ],
    [ "UdpSocket", "class_udp_socket.html", "class_udp_socket" ],
    [ "Uid", "struct_uid.html", "struct_uid" ],
    [ "UnableToLock", "class_unable_to_lock.html", "class_unable_to_lock" ],
    [ "UnregisteredSession", "class_unregistered_session.html", "class_unregistered_session" ],
    [ "User", "struct_user.html", "struct_user" ],
    [ "UserManager", "class_user_manager.html", "class_user_manager" ],
    [ "UserProtocol", "class_user_protocol.html", "class_user_protocol" ],
    [ "UserSession", "class_user_session.html", "class_user_session" ],
    [ "UserSmartPhone", "struct_user_smart_phone.html", "struct_user_smart_phone" ]
];